# Generated by Django 5.1.7 on 2025-03-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_atributes_product_attributes_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
