# Generated by Django 5.1.7 on 2025-04-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_payment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
